# Generated by Django 5.2.3 on 2025-07-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_otp_code_remove_user_otp_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
